### ISSUE TITLE
Ability to set damage/aimpunch scale per weapon type

### ISSUE THREAD

**Issue by spitice** [spitice/throwing-melee-damage#3]
In addition to the current damage calculation and aimpunch angle generation code, it would be nice to have those control knobs that change the scale of damage/aimpunch fx for each weapon type.

In regards to the damage scaling, perhaps, the plugin users unlikely change self/FF damages over different weapon types so it seems to be enough to only have CVars for damages to enemy players.

**New ConVars:**

```
sm_throwing_melee_damage_mult_axe 1
sm_throwing_melee_damage_mult_hammer 1
sm_throwing_melee_damage_mult_spanner 1

sm_throwing_melee_critical_chance_override_axe -1  // -1 to inherit common crit chance
sm_throwing_melee_critical_chance_override_hammer -1
sm_throwing_melee_critical_chance_override_spanner -1

sm_throwing_melee_aimpunch_mult_axe 1
sm_throwing_melee_aimpunch_mult_hammer 1
sm_throwing_melee_aimpunch_mult_spanner 1
```

**Subtasks:**

- [x] Implement the code
- [x] Update the manual test & perform it
- [x] Update the doc
